import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/Navbar";
import Hero   from "./components/Hero";
 import Header from "./components/Header";
import Card1  from "./components/Card1";
import Card2  from "./components/Card2";
import Pictures from "./components/Pictures";
import Starts from "./components/Starts";
import Border from "./components/Border";
import Footer from "./components/Footer";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar/>
        <Hero/>
        <Header/> 
        <Card1/>
        <Card2/>
        <Pictures/>
        <Starts/>
        <Border/>
        <Footer/>
        {children}
       
      </body>
    </html>
  );
}